services:
  postgres:
    image: postgres:15
    container_name: notifications_postgres
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    command: >
      postgres
      -c listen_addresses='*'
      -c password_encryption=md5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notifications_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"