<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
      <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Messaging\RabbitMQ\" />
      <Folder Include="Outbox\" />
      <Folder Include="Persistence\Configurations\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
    </ItemGroup>

</Project>
