// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.API.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notifications.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notifications.API.Entities.ApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Notifications.API.Entities.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("Notifications.API.Entities.ContactType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Адрес электронной почты",
                            IsDeleted = false,
                            Name = "Email",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        },
                        new
                        {
                            Id = 2L,
                            Code = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Номер телефона",
                            IsDeleted = false,
                            Name = "Phone",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        },
                        new
                        {
                            Id = 3L,
                            Code = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Имя пользователя в Telegram",
                            IsDeleted = false,
                            Name = "Telegram",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        });
                });

            modelBuilder.Entity("Notifications.API.Entities.DeliveryStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeliveryStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Сообщение добавлено в очередь",
                            IsDeleted = false,
                            Name = "В очереди",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        },
                        new
                        {
                            Id = 2L,
                            Code = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Сообщение обрабатывается",
                            IsDeleted = false,
                            Name = "В обработке",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        },
                        new
                        {
                            Id = 3L,
                            Code = 3,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Сообщение успешно доставлено",
                            IsDeleted = false,
                            Name = "Отправлено",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        },
                        new
                        {
                            Id = 4L,
                            Code = 4,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Ошибка при отправке",
                            IsDeleted = false,
                            Name = "Ошибка",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        },
                        new
                        {
                            Id = 9999L,
                            Code = 9999,
                            CreatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335),
                            Description = "Не поддерживается",
                            IsDeleted = false,
                            Name = "Не поддерживается",
                            UpdatedAt = new DateTime(2026, 5, 7, 8, 38, 16, 289, DateTimeKind.Utc).AddTicks(3335)
                        });
                });

            modelBuilder.Entity("Notifications.API.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StorageTimeAfterSendingInHours")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Notifications.API.Entities.Recipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ContactTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeliveryStatusId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NextRetry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("DeliveryStatusId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageRecipients");
                });

            modelBuilder.Entity("Notifications.API.Entities.Attachment", b =>
                {
                    b.HasOne("Notifications.API.Entities.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Notifications.API.Entities.Recipient", b =>
                {
                    b.HasOne("Notifications.API.Entities.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notifications.API.Entities.DeliveryStatus", "DeliveryStatus")
                        .WithMany()
                        .HasForeignKey("DeliveryStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notifications.API.Entities.Message", "Message")
                        .WithMany("Recipients")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("DeliveryStatus");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Notifications.API.Entities.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
