// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  GetAuthSecureData,
  GetAuthSecureResponses,
  PostAuthApiKeyData,
  PostAuthApiKeyResponses,
  PostAuthLoginData,
  PostAuthLoginResponses,
  PostAuthLogoutData,
  PostAuthLogoutResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export class AuthService {
  public static postAuthLogin<ThrowOnError extends boolean = false>(
    options?: Options<PostAuthLoginData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<PostAuthLoginResponses, unknown, ThrowOnError>({
      url: '/auth/login',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  public static postAuthApiKey<ThrowOnError extends boolean = false>(
    options?: Options<PostAuthApiKeyData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<PostAuthApiKeyResponses, unknown, ThrowOnError>({
      url: '/auth/api-key',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  public static getAuthSecure<ThrowOnError extends boolean = false>(
    options?: Options<GetAuthSecureData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetAuthSecureResponses, unknown, ThrowOnError>({
      url: '/auth/secure',
      ...options,
    })
  }

  public static postAuthLogout<ThrowOnError extends boolean = false>(
    options?: Options<PostAuthLogoutData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
      url: '/auth/logout',
      ...options,
    })
  }
}
