// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  DeleteMessagesByIdData,
  DeleteMessagesByIdErrors,
  DeleteMessagesByIdResponses,
  GetAuthSecureData,
  GetAuthSecureErrors,
  GetMessagesByIdData,
  GetMessagesByIdErrors,
  GetMessagesByIdResponses,
  GetMessagesData,
  GetMessagesErrors,
  GetMessagesResponses,
  PostAuthApiKeyData,
  PostAuthApiKeyErrors,
  PostAuthApiKeyResponses,
  PostAuthLoginData,
  PostAuthLoginErrors,
  PostAuthLoginResponses,
  PostAuthLogoutData,
  PostAuthLogoutErrors,
  PostAuthLogoutResponses,
  PostMessagesData,
  PostMessagesErrors,
  PostMessagesResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export class AuthService {
  public static postAuthLogin<ThrowOnError extends boolean = false>(
    options?: Options<PostAuthLoginData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostAuthLoginResponses,
      PostAuthLoginErrors,
      ThrowOnError
    >({
      url: '/auth/login',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  public static postAuthApiKey<ThrowOnError extends boolean = false>(
    options?: Options<PostAuthApiKeyData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostAuthApiKeyResponses,
      PostAuthApiKeyErrors,
      ThrowOnError
    >({
      url: '/auth/api-key',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  public static getAuthSecure<ThrowOnError extends boolean = false>(
    options?: Options<GetAuthSecureData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<unknown, GetAuthSecureErrors, ThrowOnError>({
      url: '/auth/secure',
      ...options,
    })
  }

  public static postAuthLogout<ThrowOnError extends boolean = false>(
    options?: Options<PostAuthLogoutData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostAuthLogoutResponses,
      PostAuthLogoutErrors,
      ThrowOnError
    >({ url: '/auth/logout', ...options })
  }
}

export class MessagesService {
  public static getMessages<ThrowOnError extends boolean = false>(
    options?: Options<GetMessagesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<GetMessagesResponses, GetMessagesErrors, ThrowOnError>({
      url: '/messages',
      ...options,
    })
  }

  public static postMessages<ThrowOnError extends boolean = false>(
    options?: Options<PostMessagesData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      PostMessagesResponses,
      PostMessagesErrors,
      ThrowOnError
    >({
      url: '/messages',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    })
  }

  public static deleteMessagesById<ThrowOnError extends boolean = false>(
    options: Options<DeleteMessagesByIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DeleteMessagesByIdResponses,
      DeleteMessagesByIdErrors,
      ThrowOnError
    >({ url: '/messages/{id}', ...options })
  }

  public static getMessagesById<ThrowOnError extends boolean = false>(
    options: Options<GetMessagesByIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetMessagesByIdResponses,
      GetMessagesByIdErrors,
      ThrowOnError
    >({ url: '/messages/{id}', ...options })
  }
}
