// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5112' | (string & {});
};

export type LoginRequest = {
    apiKey?: string | null;
};

export type PostAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostAuthApiKeyData = {
    body?: string;
    path?: never;
    query?: never;
    url: '/auth/api-key';
};

export type PostAuthApiKeyResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetAuthSecureData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/secure';
};

export type GetAuthSecureResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type GetTestResponses = {
    /**
     * Success
     */
    200: string;
};

export type GetTestResponse = GetTestResponses[keyof GetTestResponses];

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Success
     */
    200: string;
};

export type GetResponse = GetResponses[keyof GetResponses];
