// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5112' | (string & {})
}

export type ApiKeyResponse = {
  key?: string | null
}

export type AuthResponse = {
  owner?: string | null
  desc?: string | null
  createBy?: string | null
  createdAt?: string
  updatedAt?: string
}

export type LoginRequest = {
  apiKey?: string | null
}

export type ProblemDetails = {
  type?: string | null
  title?: string | null
  status?: number | null
  detail?: string | null
  instance?: string | null
  [key: string]: unknown
}

export type SecureResponse = {
  message?: string | null
  owner?: string | null
  desc?: string | null
  createdAt?: string | null
  updatedAt?: string | null
  createdBy?: string | null
}

export type PostAuthLoginData = {
  body?: LoginRequest
  path?: never
  query?: never
  url: '/auth/login'
}

export type PostAuthLoginErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors]

export type PostAuthLoginResponses = {
  /**
   * Success
   */
  200: AuthResponse
}

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses]

export type PostAuthApiKeyData = {
  body?: string
  path?: never
  query?: {
    desc?: string
    createBy?: string
  }
  url: '/auth/api-key'
}

export type PostAuthApiKeyErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostAuthApiKeyError = PostAuthApiKeyErrors[keyof PostAuthApiKeyErrors]

export type PostAuthApiKeyResponses = {
  /**
   * Success
   */
  200: ApiKeyResponse
}

export type PostAuthApiKeyResponse = PostAuthApiKeyResponses[keyof PostAuthApiKeyResponses]

export type GetAuthSecureData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/secure'
}

export type GetAuthSecureErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type GetAuthSecureError = GetAuthSecureErrors[keyof GetAuthSecureErrors]

export type GetAuthSecureResponses = {
  /**
   * Success
   */
  200: SecureResponse
}

export type GetAuthSecureResponse = GetAuthSecureResponses[keyof GetAuthSecureResponses]

export type PostAuthLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/logout'
}

export type PostAuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors]

export type PostAuthLogoutResponses = {
  /**
   * No Content
   */
  204: void
}

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses]
