// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:5112' | (string & {})
}

export type ApiKeyResponse = {
  key?: string | null
}

export type AuthResponse = {
  owner?: string | null
  desc?: string | null
  createBy?: string | null
  createdAt?: string
  updatedAt?: string
}

export type CreateApiKeyRequest = {
  owner?: string | null
  desc?: string | null
  createdBy?: string | null
}

export type CreateMessageRequest = {
  subject?: string | null
  messageBody?: string | null
  storageTimeAfterSendingInHours?: number
  recipients?: Array<RecipientRequestData> | null
}

export type CreateMessageResponse = {
  messageId?: number
  recipientsCount?: number
}

export type LoginRequest = {
  apiKey?: string | null
}

export type MessageResponse = {
  id?: number
  subject?: string | null
  messageBody?: string | null
  storageTimeAfterSendingInHours?: number
  createdAt?: string
  updatedAt?: string
  recipients?: Array<RecipientResponseData> | null
}

export type ProblemDetails = {
  type?: string | null
  title?: string | null
  status?: number | null
  detail?: string | null
  instance?: string | null
  [key: string]: unknown
}

export type RecipientRequestData = {
  contactTypeId?: number
  contactData?: string | null
}

export type RecipientResponseData = {
  id?: number
  contactTypeId?: number
  contactData?: string | null
  deliveryStatusId?: number
}

export type PostAuthLoginData = {
  body?: LoginRequest
  path?: never
  query?: never
  url: '/auth/login'
}

export type PostAuthLoginErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors]

export type PostAuthLoginResponses = {
  /**
   * Success
   */
  200: AuthResponse
}

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses]

export type PostAuthApiKeyData = {
  body?: CreateApiKeyRequest
  path?: never
  query?: never
  url: '/auth/api-key'
}

export type PostAuthApiKeyErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostAuthApiKeyError = PostAuthApiKeyErrors[keyof PostAuthApiKeyErrors]

export type PostAuthApiKeyResponses = {
  /**
   * Success
   */
  200: ApiKeyResponse
}

export type PostAuthApiKeyResponse = PostAuthApiKeyResponses[keyof PostAuthApiKeyResponses]

export type GetAuthSecureData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/secure'
}

export type GetAuthSecureErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type GetAuthSecureError = GetAuthSecureErrors[keyof GetAuthSecureErrors]

export type PostAuthLogoutData = {
  body?: never
  path?: never
  query?: never
  url: '/auth/logout'
}

export type PostAuthLogoutErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors]

export type PostAuthLogoutResponses = {
  /**
   * No Content
   */
  204: void
}

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses]

export type GetMessagesData = {
  body?: never
  path?: never
  query?: never
  url: '/messages'
}

export type GetMessagesErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type GetMessagesError = GetMessagesErrors[keyof GetMessagesErrors]

export type GetMessagesResponses = {
  /**
   * Success
   */
  200: Array<MessageResponse>
}

export type GetMessagesResponse = GetMessagesResponses[keyof GetMessagesResponses]

export type PostMessagesData = {
  body?: CreateMessageRequest
  path?: never
  query?: never
  url: '/messages'
}

export type PostMessagesErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type PostMessagesError = PostMessagesErrors[keyof PostMessagesErrors]

export type PostMessagesResponses = {
  /**
   * Success
   */
  200: CreateMessageResponse
}

export type PostMessagesResponse = PostMessagesResponses[keyof PostMessagesResponses]

export type DeleteMessagesByIdData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/messages/{id}'
}

export type DeleteMessagesByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type DeleteMessagesByIdError = DeleteMessagesByIdErrors[keyof DeleteMessagesByIdErrors]

export type DeleteMessagesByIdResponses = {
  /**
   * No Content
   */
  204: void
}

export type DeleteMessagesByIdResponse =
  DeleteMessagesByIdResponses[keyof DeleteMessagesByIdResponses]

export type GetMessagesByIdData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/messages/{id}'
}

export type GetMessagesByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails
}

export type GetMessagesByIdError = GetMessagesByIdErrors[keyof GetMessagesByIdErrors]

export type GetMessagesByIdResponses = {
  /**
   * Success
   */
  200: MessageResponse
}

export type GetMessagesByIdResponse = GetMessagesByIdResponses[keyof GetMessagesByIdResponses]
