<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Notifications.Worker-b54f0145-e3f5-4361-9590-dcab70f90142</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Notifications.Contracts\Notifications.Contracts.csproj" />
      <ProjectReference Include="..\Notifications.Core\Notifications.Core.csproj" />
      <ProjectReference Include="..\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Consumers\" />
      <Folder Include="Jobs\" />
    </ItemGroup>
</Project>
